# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://hunterwalden.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: /HunterWalden

# Title of the Site
title: Hunter Walden
# Description of the Site
description: A passionate software developer looking to start my career
# URL of Image of the Site
site-image: /assets/images/meta.jpg
meta-description: A portfolio website for Hunter Walden, software developer
# Keywords of the Site
site-keywords: Portfolio, Programmer
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://raw.githubusercontent.com/HunterWalden/HunterWalden/master/assets/images/header.PNG

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: hunterawalden@gmail.com
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  HunterWalden
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Hunter Walden
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: I discovered coding in 2014 and haven't stopped since. I saw my first source code in my junior year of high school and immediately knew I had found my passion. I taught myself C++ by adding dozens of features to the Impressive Title source code through commissions and personal projects. After graduating high school, I continued my commission work as I earned my Bachelor's degree in Computer Science, padding my existing knowledge with good coding practices and advanced concepts. In 2021 I began development on my own program, an editor utility made for Impressive Title servers, allowing me to expand my knowledge further by applying concepts to real-life coding problems. Though my experience is primarily C++, I worked with several other languages in college and I taught myself most of what I know through hands-on work. I am confident in my ability to read code syntax and follow logic flow in order to adapt to new languages and environments. I am eager for the opportunity to become part of a team and both showcase my abilities and further expand my skillset.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/HunterWalden

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
